# Generated by Django 4.0.4 on 2022-09-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=2000, null=True)),
                ('twitter', models.URLField(blank=True, max_length=2000, null=True)),
                ('instagram', models.URLField(blank=True, max_length=2000, null=True)),
                ('youtube', models.URLField(blank=True, max_length=2000, null=True)),
                ('vk', models.URLField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('term_and_condition', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logo')),
            ],
        ),
    ]
